// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDvRkUA863-HZtQoEQ-D2ylum-Ip00B9JQ',
//     appId: '1:377163622562:web:36408f95ea4c6158dd4ffb',
//     messagingSenderId: '377163622562',
//     projectId: 'acadimiat-a72ba',
//     authDomain: 'acadimiat-a72ba.firebaseapp.com',
//     storageBucket: 'acadimiat-a72ba.appspot.com',
//     measurementId: 'G-MYN3NSV20N',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDu5HFWrvUo5zma9qRkAOJ31M3gafSRIR0',
//     appId: '1:377163622562:android:5001cc7c8d4fef1bdd4ffb',
//     messagingSenderId: '377163622562',
//     projectId: 'acadimiat-a72ba',
//     storageBucket: 'acadimiat-a72ba.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAla8gc9OB5M0bGVvh_U4V5HRoR7mWr_5A',
//     appId: '1:377163622562:ios:632bc01aa3b6aebddd4ffb',
//     messagingSenderId: '377163622562',
//     projectId: 'acadimiat-a72ba',
//     storageBucket: 'acadimiat-a72ba.appspot.com',
//     androidClientId: '377163622562-e8tufa75ph956qesr99na2o576j5c11v.apps.googleusercontent.com',
//     iosClientId: '377163622562-892g9qar9a02d4i37top5s7o397lnio9.apps.googleusercontent.com',
//     iosBundleId: 'co.elt.acadmiat',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAla8gc9OB5M0bGVvh_U4V5HRoR7mWr_5A',
//     appId: '1:377163622562:ios:632bc01aa3b6aebddd4ffb',
//     messagingSenderId: '377163622562',
//     projectId: 'acadimiat-a72ba',
//     storageBucket: 'acadimiat-a72ba.appspot.com',
//     androidClientId: '377163622562-e8tufa75ph956qesr99na2o576j5c11v.apps.googleusercontent.com',
//     iosClientId: '377163622562-892g9qar9a02d4i37top5s7o397lnio9.apps.googleusercontent.com',
//     iosBundleId: 'co.elt.acadmiat',
//   );
// }
