// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1uJGED-54yd9xGCQEkdVtq1kT1WA891Y',
    appId: '1:258278091097:web:9a96a63cc26b527dd70448',
    messagingSenderId: '258278091097',
    projectId: 'jahezkw-8a5cf',
    authDomain: 'jahezkw-8a5cf.firebaseapp.com',
    storageBucket: 'jahezkw-8a5cf.appspot.com',
    measurementId: 'G-VC9CTPSXBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99YzO0y-5FAeSKI7PmLL9ALTuaEQJWp4',
    appId: '1:258278091097:android:6c55ba6ab6b03fc0d70448',
    messagingSenderId: '258278091097',
    projectId: 'jahezkw-8a5cf',
    storageBucket: 'jahezkw-8a5cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4hu2IdPw83lI9zKJd7bve9IH5EJh3ZM0',
    appId: '1:258278091097:ios:8899cbfdb6f78308d70448',
    messagingSenderId: '258278091097',
    projectId: 'jahezkw-8a5cf',
    storageBucket: 'jahezkw-8a5cf.appspot.com',
    iosBundleId: 'co.jahezkw.jahezkw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4hu2IdPw83lI9zKJd7bve9IH5EJh3ZM0',
    appId: '1:258278091097:ios:6944d096d919a18bd70448',
    messagingSenderId: '258278091097',
    projectId: 'jahezkw-8a5cf',
    storageBucket: 'jahezkw-8a5cf.appspot.com',
    iosBundleId: 'co.elt.acadmiat',
  );
}
